### ISSUE TITLE
Add option to open different orthoview in FSLEYES

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/manual-correction#10]
When there are more than one contrast, it is extremely useful to have both contrasts opened to generate the manual segmentation. Example below:

![Screen Shot 2023-02-10 at 11 43 24 AM](https://user-images.githubusercontent.com/2482071/218147860-6544f203-8bbb-4d61-8d34-71358e453fe9.png)

To generate this display, see [this example](https://github.com/ivadomed/model_seg_ms_mp2rage/issues/56), as well as relevant discussion in [FSL mailing list](https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2301&F=5496681621512503&L=FSL&O=D&P=31427&X=3FB009402978E6EF53&Y=julien.cohenadad%40gmail.com).

**Comment by valosekj** [comment]
Great suggestion! Thank you! I will implement this feature.

**Comment by valosekj** [comment]
Implemented in https://github.com/spinalcordtoolbox/manual-correction/pull/13
