### ISSUE TITLE
With option load other contrast, opens wrong lesion segmentation of other contrast

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/manual-correction#11]
## Description

When specifying in the config list t2w and using the option `-load-other-contrast`, the segmentation of the other contrast is opend (eg PSIR) and not T2w.

**Comment by valosekj** [comment]
Yes, you are right. I'm aware of this, see [my comment](https://github.com/spinalcordtoolbox/manual-correction/pull/8#issue-1563463555):

> The PR also contains ["hacky" commit](https://github.com/spinalcordtoolbox/manual-correction/commit/28ada98b99e297aed4ca504fec659968b93ed883) for the opening of the already existing PSIR segmentations. Once @mchen1110 finishes her work with these PSIR segmentations, I will remove the commit and merge the PR.

**Comment by valosekj** [comment]
Resolved in https://github.com/spinalcordtoolbox/manual-correction/commit/7da2d5684fb62354dd56cc2d40599d0d6a6e082e
