### ISSUE TITLE
Fix description of `manual_correction.py`

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/manual-correction#12]
Here are a few probems in the description:

- [ ] `-path-derivative` and `-path-out` are kind of redundant/confusing. They could be merged

- [x] There are a few typos in `-path-derivatives`:
    * Path to the 'derivatives' BIDS-complaint folder where the corrected labels will be saved. Default: derivatives/label**sN**ote: if the provided folder (e.g., 'derivatives/labels') does not already exist, it will be create**d.N**ote: if segmentation or labels files already exist and you would like to correct them, provide path to them within this flag.  - fixed in https://github.com/spinalcordtoolbox/manual-correction/commit/da9df494c8d0680d97c9fea371338546eb2d74fc 

-  [x] `- load other contrast`
    - how does it find the contrast? , is it or the BIDS. Could be an exmple of the contrast name and filename - fixed in https://github.com/spinalcordtoolbox/manual-correction/commit/a375c101c2f3dab0dd95d94474384bd3570e785c

**Comment by valosekj** [comment]
Good points, thank you! I will address them.

**Comment by valosekj** [comment]
Description fixed. The point about `-path-derivative` and `-path-out` moved to https://github.com/spinalcordtoolbox/manual-correction/issues/32.

--> closing this issue
