### ISSUE TITLE
`manual_correction.py` - add option to update `json` sidecars

### ISSUE THREAD

**Issue by naga-karthik** [spinalcordtoolbox/manual-correction#3]
It would be useful to have a function that updates the existing json sidecars existing in the derivatives folder instead of creating a new one or overwriting the existing ones. 

This is important because if we modify the segmentations, then, the names of the author modifying the dataset along with the original author of the segmentations should exist in the json sidecar (the current script creates a new json file with the name of the modifying author).

**Comment by valosekj** [comment]
Excellent point, Naga! Agree.

**Comment by valosekj** [comment]
Closing --> further discussion in the parallel issue: https://github.com/spinalcordtoolbox/manual-correction/issues/34
