### ISSUE TITLE
`-path-derivative` and `-path-out` are redundant

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/manual-correction#32]
Originally posted in https://github.com/spinalcordtoolbox/manual-correction/issues/12#issue-1580052623:

> `-path-derivative` and `-path-out` are kind of redundant/confusing. They could be merged

**Comment by NathanMolinier** [comment]
I believe these flags are not redundant, indeed:
- `-path-derivative` should be used to specify the path from the bids dataset to the derivatives folder we want to use (ex: `derivatives/labels` or `derivatives/labels_softseg` see --> [spinegeneric](https://github.com/spine-generic/data-multi-subject/tree/master/derivatives))
- `-path-out` should be used to specify the full path to the output folder where the modified data will be stored (ex: `/tmp/new_labels`) --> this way, the user won't be obliged to modify the current datasets

**Comment by valosekj** [comment]
That sounds doable! Could you please propose a PR?

**Comment by valosekj** [comment]
Resolved in https://github.com/spinalcordtoolbox/manual-correction/pull/43 in the context of input args refactoring.
