### ISSUE TITLE
Discuss JSON sidecar usage for correcting/verifying segmentations

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/manual-correction#34]
In the [2023-03-30](https://docs.google.com/document/d/1ItApJQfajO2lRzOU2yenWbeRg6alfsdut3J4AVVdo78/edit#heading=h.n1r80cjfe5z4) SCT meeting, we [briefly discussed](https://docs.google.com/document/d/1ItApJQfajO2lRzOU2yenWbeRg6alfsdut3J4AVVdo78/edit#heading=h.rinmmd6jk0) proposals for JSON sidecar usage (in the context of manual correction, verification, etc. of segmentations).

To summarize the points that were made:

- Empty JSON sidecar files are not allowed by BIDS
- The [intranet](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#derivatives-structure) (scroll down to bottom) currently recommends including Author and Date when first creating sidecar files.
- However, what convention should we use for  _updates_ to files? (e.g. corrections/verifications)
    - Do we change the existing author/date?
    - Do we use lists of different authors-date pairings?
    - Do we use a separate field for updates?
        - For example, @valosekj proposed `"VerifiedBy": "Generated automatically and visually checked by JV"` 
        - NB: How would this handle multiple verifications?
    - Do we create an entirely separate JSON sidecar file?

**Comment by valosekj** [comment]
Thanks for the summary @joshuacwnewton!

Just to add that within `sci-zurich` project, we add the author who made a correction to the `Author` field.

JSON before correction:

```json
{
        "Author": "Bob Rob",
}
```

JSON after correction:

```json
{
        "Author": "Bob Rob, Jan Valosek",
}
```

**Comment by valosekj** [comment]
@NathanMolinier proposed in https://github.com/spinalcordtoolbox/manual-correction/pull/43/commits/db9af06cdcf8abffdd932ff4608d9aaa53adf627 the following updating of the JSON sidecar:

```json
{
    "Author": "Jan Valosek",
    "Date": "2023-07-12 19:32:33"
}
{
    "Author": "Jan Valosek",
    "Date": "2023-07-12 19:34:00"
}
```

But, this seems to be not valid JSON file. The valid JSON should be:

```json
[
    {
        "Author": "Jan Valosek",
        "Date": "2023-07-12 19:32:33"
    },
    {
        "Author": "Jan Valosek",
        "Date": "2023-07-12 19:34:00"
    }
]
```

**Comment by valosekj** [comment]
We switched to the following convention in https://github.com/spinalcordtoolbox/manual-correction/pull/43:

```json
{
    "GeneratedBy": [
        {
            "Author": "Jan Valosek",
            "Date": "2023-07-14 13:43:10"
        },
        {
            "Author": "Jan Valosek",
            "Date": "2023-07-14 13:45:53"
        }
    ]
}
```

We are now appending the raters who modified the label into a list of dicsts.

**Comment by valosekj** [comment]
Closing.

Just a note. Besides `Author` and `Date` keys, we now use also `Name` and `SpatialReference` keys; see https://github.com/spinalcordtoolbox/manual-correction/pull/76 for details.
