### ISSUE TITLE
Missing files error when using `*` wildcard

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/manual-correction#35]
When using the following yml config file:

```yml
FILES_LESION:
 - sub-*_acq-ax_T2w.nii.gz
```

`manual_correction.py` script does not interpret `*` as a wildcard and prints an error about missing files:

```console
(venv) valosek@macbook-pro:~/code/manual-correction$ python manual_correction.py -config ~/data/data.neuro.polymtl.ca/dcm-zurich-lesions/compression_labels.yml -path-in ~/data/data.neuro.polymtl.ca/dcm-zurich-lesions
The following files are missing:
['/Users/valosek/data/data.neuro.polymtl.ca/dcm-zurich-lesions/sub-*/anat/sub-*_acq-ax_T2w.nii.gz']

Please check that the files listed in the yaml file and the input path are correct.

The following label files are missing:
['/Users/valosek/data/data.neuro.polymtl.ca/dcm-zurich-lesions/sub-*/anat/sub-*_acq-ax_T2w_lesion.nii.gz']

Please check that the used suffix '_lesion' is correct. If not, you can provide custom suffix using '-suffix-files-' flags.
```

But still, the script then continues.

**Comment by NathanMolinier** [comment]
I just had an issue while using wildcards with the following YAML file:
```yaml
FILES_LABEL:
- sub-*.nii.gz
```

The script is looking for a centerline file for no reason:
<img width="1076" alt="Screenshot 2023-08-18 at 2 58 52 PM" src="https://github.com/spinalcordtoolbox/manual-correction/assets/68945192/5269ed64-739d-4a0a-b3b7-7fec7424f5f6">

Do you have any ideas why @valosekj ?

**Comment by valosekj** [comment]
Weird! Can you please debug the following lines:

https://github.com/spinalcordtoolbox/manual-correction/blob/13cd3f4e599161aa1c5866d66c60a25a0f3c006a/manual_correction.py#L682-L687

**Comment by NathanMolinier** [comment]
I just did and I have that:
```
subject=''
ses=''
filename='sub-*.nii.gz'
```
And files
<img width="892" alt="Screenshot 2023-08-18 at 3 14 31 PM" src="https://github.com/spinalcordtoolbox/manual-correction/assets/68945192/0a110ece-78ff-472d-be12-3f3639accdc5">

**Comment by NathanMolinier** [comment]
This line need to be fixed 
```python
files = sorted(glob.glob(os.path.join(path_img, '**', filename),
 recursive=True))
```

**Comment by valosekj** [comment]
Good catch! You are right, `glob.glob '**'` returns all the files. But the files should be filtered based on the key (e.g., `FILES_LABELS`). We can use filtering based on `suffix_dict[task]`, as done here:

https://github.com/spinalcordtoolbox/manual-correction/blob/13cd3f4e599161aa1c5866d66c60a25a0f3c006a/manual_correction.py#L711

**Comment by NathanMolinier** [comment]
Not really, because the variable `files` should only contain path to images, not labels.

Moreover, it not clear to me how were these paths created since no `_centerline` files are available in the whole-spine dataset.
