### ISSUE TITLE
Add a new variable to be able to overwrite several files

### ISSUE THREAD

**Issue by NathanMolinier** [spinalcordtoolbox/manual-correction#42]
## Description

Currently, when modifying several files, the script is asking for each one if we want to overwrite it and it is time consumming when overwriting an entire dataset.

<img width="603" alt="Capture d’écran 2023-05-17 à 14 08 36" src="https://github.com/spinalcordtoolbox/manual-correction/assets/68945192/37e1fd02-7ae0-4649-b336-4cfe4c804d58">

## Solutions

For this reason, a variable should be implemented to enable a permanent yes for this question. Solutions could be to:

- Add an upper case Y as a response to set this variable to always `True`
- Add a flag when running the function to directly set this variable to `True`

**Comment by jcohenadad** [comment]
> Add an upper case Y as a response to set this variable to always True

I like this proposal (prevents from adding another argument), however it would not work if the job is launched on a cluster, without human interaction (but I guess this never happens for the manual correction workflow?)

**Comment by NathanMolinier** [comment]
I believe manual correction is only used in local to be able to launch the viewer

**Comment by valosekj** [comment]
Solved in #54
