### ISSUE TITLE
Add more than 20 discs labels

### ISSUE THREAD

**Issue by NathanMolinier** [spinalcordtoolbox/manual-correction#47]
## Description

Currently users are limited in term of discs labels: 20 is the maximum number allowed. This is limiting when dealing with lumbar scans or large field of view.

See subject sub-bwh083 in sct-testing-large
<img width="904" alt="Capture d’écran 2023-07-04 à 16 02 39" src="https://github.com/spinalcordtoolbox/manual-correction/assets/68945192/c36c9e5a-785c-48fc-afdc-d30580265583">

**Comment by valosekj** [comment]
I believe you can use the `-label-disc-list` flag to change the number of discs to label.

https://github.com/spinalcordtoolbox/manual-correction/blob/39785a65104ab53f5d1477fc06725c772a642358/manual_correction.py#L161-L165

**Comment by valosekj** [comment]
As discussed in person, we could change the default interval to `1:25` (25 is the max label, see our [labeling conventions](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/vertebral-labeling/labeling-conventions.html))

https://github.com/spinalcordtoolbox/manual-correction/blob/39785a65104ab53f5d1477fc06725c772a642358/manual_correction.py#L165

**Comment by valosekj** [comment]
The default value changed to `1:25` in https://github.com/spinalcordtoolbox/manual-correction/pull/43/commits/3636973a04895c5e49c20b0233f880fd66ce1b82
