### ISSUE TITLE
Keep track of correction and resume correction

### ISSUE THREAD

**Issue by NathanMolinier** [spinalcordtoolbox/manual-correction#49]
## Description

When dealing with an important number of corrections, it is not currently possible to stop the script and resume right where we stopped (the solution used for most users was to keep the terminal open and the computer turned on until the end of the correction phase).

## Solution

Since every path to the images should be in the `YML config file`, a simple solution would be to comment (using a `#`) after every correction the path to the image. Then when `manual_correction.py` is executed again the commented line will automatically be skipped.

However, this method should not be used when `wildcards` such as * are present in the YML path

**Comment by valosekj** [comment]
> ## Solution
> Since every path to the images should be in the `YML config file`, a simple solution would be to comment (using a `#`) after every correction the path to the image. Then when `manual_correction.py` is executed again the commented line will automatically be skipped.

Excellent idea!

> However, this method should not be used when wildcards such as * are present in the YML path

Good point! In this case, we could simply append the corrected images to the YML (to track which images have been corrected). For example:

```
FILES_LESION:
 - sub-*_acq-sag_T2w.nii.gz
#  - sub-001/anat/sub-001_acq-sag_T2w.nii.gz
#  - sub-002/anat/sub-002_acq-sag_T2w.nii.gz
```
