### ISSUE TITLE
Warning about missing label files - the script does not check `derivatives`

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/manual-correction#50]
When testing https://github.com/spinalcordtoolbox/manual-correction/pull/43, I get the following warning about missing label files:

```console
$ python manual_correction.py -config /Users/valosek/data/spineimage.ca/site_012/lesions_to_correct.yml -path-img /Users/valosek/data/spineimage.ca/site_012
The following label files are missing:
['/Users/valosek/data/spineimage.ca/site_012/sub-hal001/anat/sub-hal001_acq-sag_T2w_lesion.nii.gz', '/Users/valosek/data/spineimage.ca/site_012/sub-hal002/anat/sub-hal002_acq-sag_run-01_T2w_lesion.nii.gz', '/Users/valosek/data/spineimage.ca/site_012/sub-hal003/anat/sub-hal003_acq-sag_T2w_lesion.nii.gz', '/Users/valosek/data/spineimage.ca/site_012/sub-hal004/anat/sub-hal004_acq-sag_run-01_T2w_lesion.nii.gz']

Please check that the used suffix '_lesion' is correct. If not, you can provide custom suffix using '-suffix-files-' flags.
If you are creating label(s) from scratch, ignore this message.
```

The logic behind the warning is wrong because labels exist under `derivatives/labels/sub-hal001/anat/`, but the script looks to the root directory (`sub-hal001/anat/`).

**Comment by NathanMolinier** [comment]
The behavior is actually the one depicted in the help:
<img width="919" alt="Capture d’écran 2023-07-10 à 13 15 44" src="https://github.com/spinalcordtoolbox/manual-correction/assets/68945192/cf1ebab8-33c6-4260-853a-dc7576a6a1b3">

The folders `derivatives/labels/` are only added for the default output, not the labels.

You should rerun the script using this command
```bash
python manual_correction.py -config /Users/valosek/data/spineimage.ca/site_012/lesions_to_correct.yml -path-img /Users/valosek/data/spineimage.ca/site_012 -path-label /Users/valosek/data/spineimage.ca/site_012/derivatives/labels/
```

**Comment by valosekj** [comment]
Interesting is that even when I specify only `-path-img` (and not `-path-label`):

```
python manual_correction.py -config /Users/valosek/data/spineimage.ca/site_012/lesions_to_correct.yml -path-img /Users/valosek/data/spineimage.ca/site_012
```

The script is able to locate, and potentially open, the label file under `derivatives`:

```
WARNING! The file /Users/valosek/data/spineimage.ca/site_012/derivatives/labels/sub-hal001/anat/sub-hal001_acq-sag_T2w_lesion-manual.nii.gz already exists. Would you like to modify it? [y/n] y
```

**Comment by valosekj** [comment]
Resolved in https://github.com/spinalcordtoolbox/manual-correction/pull/43/commits/f6af1aa20e8efc093dd93ea97b8f1595d7499ad2.

**Comment by Kaonashi22** [comment]
Hi,

I'm having the same issue.
When I run the following command, the T2 segmentation files are not found and empty labels are created under the derivatives folder...
_python manual_correction.py -config /qc_fail.yml -path-img /data_processed/ -path-label /data_processed/derivatives/labels/_

**Error**: _If you are creating label(s) from scratch, ignore the following message.
The following label files are missing: 
['data_processed/derivatives/labels/sub-ER240/anat/sub-ER240_T2_seg.nii.gz', '/data_processed/derivatives/labels/sub-GE200/anat/sub-GE200_T2_seg.nii.gz']
Please check that the used suffix ['_seg'] is correct. If not, you can provide custom suffix using '-suffix-files-' flags._

**Comment by Kaonashi22** [comment]
Problem solved!

**Comment by valosekj** [comment]
> Problem solved!

Could you please provide details of how you solved the issue? It could help future users.

**Comment by Kaonashi22** [comment]
Sure, I actually gave the wrong path to the labels; the command should be :
python manual_correction.py -config /qc_fail.yml -path-img /data_processed/ -path-label /data_processed

**Comment by valosekj** [comment]
Great, thanks! Just FYI, I added an extra warning for this case in https://github.com/spinalcordtoolbox/manual-correction/commit/5950172fb2a3a83fab9af755e19c5795d203a128.
