### ISSUE TITLE
Add color option as additional argument for FSLeyes

### ISSUE THREAD

**Issue by naga-karthik** [spinalcordtoolbox/manual-correction#6]
Some GT lesion segmentations might be soft so it would be a bit easier if we can specify the color we want to open the segmentation file with instead of manually choosing the color in FSLeyes. 

This is only a minor update to the existing script and is implemented in 8f1ffb862ead7df3e56fc0f49c1c35a168d8aa3e.

**Comment by valosekj** [comment]
@naga-karthik Thank you for the implementation of this feature! I tested your commit, and it works fine! --> closing this issue as solved.
