### ISSUE TITLE
Handle KeyErrors more gracefully if user marks `FILES_REG` as a `qc_fail.yml`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/manual-correction#71]
Brought up during SCT Course review: https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit?disco=AAAA_ji8hGs

Maybe instead of erroring out, we could just emit a warning and skip the entry?

**Comment by valosekj** [comment]
Good catch! Agree. The handling of unsupported keys such as `FILES_REG` could be improved.
