### ISSUE TITLE
Add parameter to min/max image intensity in FSLEYES

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/manual-correction#9]
## Description
For the same dataset, it would be useful to specify the min/max intensity of the image in FSLEYES so the user don't have to specify it everytime.

**Comment by valosekj** [comment]
Good point. I will add this option. But instead of specifying absolute min/max values (which can vary across subjects), I'm inclined to specify the percentage range, for example, 10-70%.
