### ISSUE TITLE
Merge QCs across labeling sessions?

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/manual-correction#91]
When interrupting a session and then resuming, the QC folder is not the same (bc it uses date/time). So, for labeling tasks with a LOT of subjects, that requires multiple breaks, we end up with a bunch of QC folders, eg:

<img width="292" alt="image" src="https://github.com/spinalcordtoolbox/manual-correction/assets/2482071/6df0d08c-f189-4a10-9904-b245d1bfd0ac">

Which makes it (i) cumbersome to review and (ii) cumbersome to share with collaborators.

Wouldn't it be desirable to merge all labeling session into the same QC folder?

**Comment by Kaonashi22** [comment]
Sure, merging all labeling session into the same QC folder would be more convenient

**Comment by valosekj** [comment]
Thanks for reporting this!

> Wouldn't it be desirable to merge all labeling session into the same QC folder?

Agree. Since this is a single line change, I proposed a PR: https://github.com/spinalcordtoolbox/manual-correction/pull/92
